name: 📝 Documentation Issue
description: Documentation is unclear or otherwise insufficient.
labels:
  - documentation
  - requires triage
body:
  - type: markdown
    attributes:
      value: >-
        Have a question?  This is the TypeORM issue tracker - and not the right
        place for general support or questions.  Instead, check the [“Support"
        Documentation](https://github.com/typeorm/typeorm/blob/master/docs/support.md

        ) on the best places to ask questions!
  - type: textarea
    id: details
    attributes:
      label: What was unclear or otherwise insufficient?
      description: >-
        If relevant, Please be clear about the documentation file, as well as
        the location within the file. Link to the documentation in the
        repository.
      placeholder: >-
        If the page does not exist, please be clear why a new documentation
        section is needed.
    validations:
      required: true
  - type: textarea
    id: recommendation
    attributes:
      label: Recommended Fix
      description: How should we fix this documentation issue?
      placeholder: Should we add examples, clarify the language, or drop the page entirely?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
  - type: dropdown
    id: pr
    attributes:
      label: Are you willing to resolve this issue by submitting a Pull Request?
      options:
        - Yes, I have the time, and I know how to start.
        - >-
          Yes, I have the time, but I don't know how to start. I would need
          guidance.
        - >-
          No, I don’t have the time, but I can support (using donations)
          development.
        - >-
          No, I don’t have the time and I’m okay to wait for the community /
          maintainers to resolve this issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |-
        Remember that first-time contributors are welcome! 🙌

        👋 Have a great day and thank you for the documentation problem report!
